# Generated by Django 4.2.5 on 2023-10-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupermercadoApp', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
