# Generated by Django 4.2.5 on 2023-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupermercadoApp', '0003_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clientes'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empleados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores'),
        ),
    ]
